### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72)

### ISSUE THREAD

**Issue by air66design** [understrap/understrap#1070]
Hi 
I appreciate this is something to do with my environment, but i'm not sure what has changed. I came to run gulp watch and got the below error.

Any help would be much appreciated.

Thanks
Dave

D:\Air66 Files\dev_sites\www.isuna.dev.cc\wp-content\themes\understrap-master\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\Air66 Files\dev_sites\www.isuna.dev.cc\wp-content\themes\understrap-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\Air66 Files\dev_sites\www.isuna.dev.cc\wp-content\themes\understrap-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Air66 Files\dev_sites\www.isuna.dev.cc\wp-content\themes\understrap-master\node_modules\gulp-sass\index.js:162:21)
    at Module._compile (internal/modules/cjs/loader.js:956:30)

**Comment by air66design** [comment]
Hi, Sorry for the above I've managed to fix it.
Not sure if this is the correct way but i uninstalled Node - re installed it and Gulp now is working thanks
