### ISSUE TITLE
errors with npm install

### ISSUE THREAD

**Issue by air66design** [understrap/understrap#1074]
Hi

was hoping someone could help. I can't seem to install understrap.
I've got node v 12.13.1 installed
gulp v 
CLI v 2.2.0
Local Version: 4.0.2

i keep getting the following when trying to run gulp watch: i have also tried rebuilding the node-sass as it says with no luck. I've also deleted the node modules and re installed still no luck.

Time Elapsed 00:00:30.11
gyp info ok
Installed to D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap\node_modules\node-sass\vendor\win32-x64-72\binding.node
node-sass@4.13.0 D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap\node_modules\node-sass
PS D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap> gulp watch
D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap\node_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (D:\Air66 Files\dev_sites\www.test.dev.cc\wp-content\themes\understrap\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

Thanks in advance

**Comment by air66design** [comment]
eventually solved it - it seemed i had a version of NPM running using NVM and that version was 10.x - i removed it now it is running.
