### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)

### ISSUE THREAD

**Issue by piotrszczesniak** [understrap/understrap#1231]
Hello, I am setting up local environment using xammp and I get this after I run: npm install:

PS C:\xampp\htdocs\przydonicy\wp-content\themes\przydonicy-theme> npm install

> understrap@0.9.4 postinstall
> gulp copy-assets

C:\xampp\htdocs\przydonicy\wp-content\themes\przydonicy-theme\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (C:\xampp\htdocs\przydonicy\wp-content\themes\przydonicy-theme\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\xampp\htdocs\przydonicy\wp-content\themes\przydonicy-theme\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\xampp\htdocs\przydonicy\wp-content\themes\przydonicy-theme\node_modules\gulp-sass\index.js:162:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code 1
npm ERR! path C:\xampp\htdocs\przydonicy\wp-content\themes\przydonicy-theme
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c gulp copy-assets

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\piotr\AppData\Local\npm-cache\_logs\2020-11-21T19_58_54_579Z-debug.log

Can I ask for advice on how to make all modules installed and get up and running with gulp watch-bs?

**Comment by IanDelMar** [comment]
Use the master branch files to install UnderStrap (the master branch version of UnderStrap should use node-sass@4.14) or delete the `package-lock.json` before `npm install` so you are not locked to node-sass@4.11.

**Comment by piotrszczesniak** [comment]
> Use the master branch files to install UnderStrap (the master branch version of UnderStrap should use node-sass@4.14) or delete the `package-lock.json` before `npm install` so you are not locked to node-sass@4.11.

I'll try with the master as a first step and see if that works, thanks!

**Comment by piotrszczesniak** [comment]
It works perfectly fine - thanks a lot for quick support 🥇

**Comment by IanDelMar** [comment]
Great! If it works now, would you please close the issue? Thank you!

**Comment by piotrszczesniak** [comment]
Sure, thank you!
