### ISSUE TITLE
Error: The target selector was not found. Use "@extend .alert-success !optional" to avoid this error.

### ISSUE THREAD

**Issue by isaklafleur** [understrap/understrap#1497]
I get numerous errors on this file _woocommerce.scss in the understrap child folder. I run the bs5 beta version. I use woocommerce, latest version. To avoid this errors I follow the instructions in the error message and adds !optional on all lines necessary (approx 6 errors in this file) and after this the error disapears. Do you have any idea how to fix it?

```
Error: The target selector was not found.
Use "@extend .alert-success !optional" to avoid this error.
   ╷
36 │   @extend .alert-success;
   │   ^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\sass\assets\understrap\theme\_woocommerce.scss 36:3  root stylesheet
```

```
PS C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child> npm i

> nodemon@2.0.12 postinstall C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 591 packages from 433 contributors and audited 594 packages in 13.264s

64 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child> npm run watch

> understrap-child@1.1.0-beta watch C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> npm-run-all --parallel watch-run-*


> understrap-child@1.1.0-beta watch-run-js C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> nodemon --watch src/js/ --ext js --exec "npm-run-all js"


> understrap-child@1.1.0-beta watch-run-css C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> nodemon --watch sass/ --ext scss --exec "npm-run-all css"

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): sass\**\*
[nodemon] watching extensions: scss
[nodemon] starting `npm-run-all css`
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\js\**\*
[nodemon] watching extensions: js
[nodemon] starting `npm-run-all js`

> understrap-child@1.1.0-beta js C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> npm-run-all js-compile js-minify


> understrap-child@1.1.0-beta css C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> npm-run-all css-compile css-postcss css-minify


> understrap-child@1.1.0-beta js-compile C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> rollup --config src/build/rollup.config.js --sourcemap


> understrap-child@1.1.0-beta css-compile C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/child-theme.scss:css/child-theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css


C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\src\js\bootstrap.js, C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\src\js\skip-link-focus-fix.js, C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\src\js\custom-javascript.js → js\child-theme.js...
created js\child-theme.js in 1.3s

> understrap-child@1.1.0-beta js-minify C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
> terser --config-file src/build/terser.config.json --output js/child-theme.min.js js/child-theme.js

Error: The target selector was not found.
Use "@extend .alert-success !optional" to avoid this error.
   ╷
36 │   @extend .alert-success;
   │   ^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\sass\assets\understrap\theme\_woocommerce.scss 36:3  root stylesheet
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! understrap-child@1.1.0-beta css-compile: `sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/child-theme.scss:css/child-theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css`    
npm ERR! Exit status 65
npm ERR!
npm ERR! Failed at the understrap-child@1.1.0-beta css-compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\isake\AppData\Roaming\npm-cache\_logs\2021-11-02T20_59_20_851Z-debug.log
ERROR: "css-compile" exited with 65.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap-child@1.1.0-beta css: `npm-run-all css-compile css-postcss css-minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap-child@1.1.0-beta css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\isake\AppData\Roaming\npm-cache\_logs\2021-11-02T20_59_20_891Z-debug.log
ERROR: "css" exited with 1.
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] clean exit - waiting for changes before restart

```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'css'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'precss', 'css', 'postcss' ]
5 info lifecycle understrap-child@1.1.0-beta~precss: understrap-child@1.1.0-beta
6 info lifecycle understrap-child@1.1.0-beta~css: understrap-child@1.1.0-beta
7 verbose lifecycle understrap-child@1.1.0-beta~css: unsafe-perm in lifecycle true
8 verbose lifecycle understrap-child@1.1.0-beta~css: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child\node_modules\.bin;C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\AutoFirma\AutoFirma;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\PowerShell\7\;C:\Users\isake\AppData\Local\Microsoft\WindowsApps;C:\Users\isake\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\isake\AppData\Roaming\Composer\vendor\bin;C:\xampp\php\php.exe;C:\ProgramData\ComposerSetup\bin;C:\Users\isake\AppData\Local\Yarn\bin
9 verbose lifecycle understrap-child@1.1.0-beta~css: CWD: C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
10 silly lifecycle understrap-child@1.1.0-beta~css: Args: [ '/d /s /c', 'npm-run-all css-compile css-postcss css-minify' ]
11 silly lifecycle understrap-child@1.1.0-beta~css: Returned: code: 1  signal: null
12 info lifecycle understrap-child@1.1.0-beta~css: Failed to exec css script
13 verbose stack Error: understrap-child@1.1.0-beta css: `npm-run-all css-compile css-postcss css-minify`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid understrap-child@1.1.0-beta
15 verbose cwd C:\xampp\htdocs\wp-content\themes\theuntamed-understrap-child
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "css"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error understrap-child@1.1.0-beta css: `npm-run-all css-compile css-postcss css-minify`
22 error Exit status 1
23 error Failed at the understrap-child@1.1.0-beta css script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

![image](https://user-images.githubusercontent.com/10033653/139952059-414c83e1-e83d-4541-a3f6-0b4170df90cd.png)

**Comment by isaklafleur** [comment]
![image](https://user-images.githubusercontent.com/10033653/139952109-81ddd3a7-8411-4339-823a-4d2ce9d4c9cb.png)

**Comment by bacoords** [comment]
I believe this is an issue with the Understrap child pulling in the develop branch instead of the actual main branch: https://github.com/understrap/understrap-child/blob/main/package.json#L63

It should be  `"understrap": "github:understrap/understrap"` on line 63 so that it pulls in the correct version of Understrap.
