### ISSUE TITLE
Please provide a short summary of the problem (approx. 50 characters)

### ISSUE THREAD

**Issue by ivancunha** [understrap/understrap#1524]
I don't know if this is a problem in my local environment of not.
Everything was fine in another project 2 weeks ago.
After that, the only thing I did was to update the git version, and probably the updates from the OS.

I'm in Linux Mint, using LocalByFlyWheel.
nvm v0.39.0
npm I used all the latest LTS v16.13.0, v14.18.1, v12.22.7, and v10.24.1
git v2.34.1 but also tried 2.25.x,2.17.x and other

I install the latest wordpress version with LocalByFlywheel.
Then I go to Appearence->Themes-> Add New and install the Understrap theme.
In Terminal in the understrap folder I run "npm install", and get the usual:

> npm WARN old lockfile 
> npm WARN old lockfile The package-lock.json file was created with an old version of npm,
> npm WARN old lockfile so supplemental metadata must be fetched from the registry.
> npm WARN old lockfile 
> npm WARN old lockfile This is a one-time fix-up, please be patient...
> npm WARN old lockfile 
> npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
> 
> added 591 packages, and audited 592 packages in 23s
> 
> 63 packages are looking for funding
>   run `npm fund` for details
> 
> 6 vulnerabilities (4 moderate, 2 high)
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.

Then I run "npm run watch" and get:

> > understrap@1.0.1 watch
> > npm-run-all --parallel watch-run-*
> 
> 
> > understrap@1.0.1 watch-run-js
> > nodemon --watch src/js/ --ext js --exec "npm-run-all js"
> 
> 
> > understrap@1.0.1 watch-run-css
> > nodemon --watch sass/ --ext scss --exec "npm-run-all css"
> 
> [nodemon] 2.0.12
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): src/js/**/*
> [nodemon] watching extensions: js
> [nodemon] starting `npm-run-all js`
> [nodemon] 2.0.12
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): sass/**/*
> [nodemon] watching extensions: scss
> [nodemon] starting `npm-run-all css`
> 
> > understrap@1.0.1 js
> > npm-run-all js-compile js-minify
> 
> 
> > understrap@1.0.1 css
> > npm-run-all css-compile css-postcss css-minify
> 
> 
> > understrap@1.0.1 js-compile
> > rollup --config src/build/rollup.config.js --sourcemap
> 
> 
> > understrap@1.0.1 css-compile
> > sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/theme.scss:css/theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css
> 
> 
> /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/src/js/bootstrap.js, /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/src/js/skip-link-focus-fix.js, /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/src/js/custom-javascript.js → js/theme.js...
> [!] (plugin babel) BrowserslistError: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
> src/js/bootstrap.js
> BrowserslistError: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
>     at unknownQuery (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:285:10)
>     at /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:372:11
>     at Array.reduce (<anonymous>)
>     at resolve (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:318:18)
>     at browserslist (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:444:21)
>     at resolveTargets (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/@babel/helper-compilation-targets/lib/index.js:168:20)
>     at getTargets (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/@babel/helper-compilation-targets/lib/index.js:212:27)
>     at resolveTargets (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/@babel/core/lib/config/resolve-targets.js:62:50)
>     at loadPrivatePartialConfig (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/@babel/core/lib/config/partial.js:112:49)
>     at loadPrivatePartialConfig.next (<anonymous>)
> 
> ERROR: "js-compile" exited with 1.
> ERROR: "js" exited with 1.
> [nodemon] app crashed - waiting for file changes before starting...
> 
> > understrap@1.0.1 css-postcss
> > postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"
> 
> Error [BrowserslistError]: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
>     at unknownQuery (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:285:10)
>     at /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:372:11
>     at Array.reduce (<anonymous>)
>     at resolve (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:318:18)
>     at browserslist (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/browserslist/index.js:444:21)
>     at Browsers.parse (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/autoprefixer/lib/browsers.js:54:12)
>     at new Browsers (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/autoprefixer/lib/browsers.js:42:26)
>     at loadPrefixes (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/autoprefixer/lib/autoprefixer.js:113:20)
>     at Object.prepare (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/autoprefixer/lib/autoprefixer.js:127:22)
>     at /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/node_modules/postcss/lib/lazy-result.js:149:39 {
>   browserslist: true
> }
> ERROR: "css-postcss" exited with 1.
> ERROR: "css" exited with 1.
> [nodemon] app crashed - waiting for file changes before starting...

So, with these errors, I download the zip from github repo and run npm install with the same result and then npm run watch without errors.
> 
> > understrap@1.0.1 watch
> > npm-run-all --parallel watch-run-*
> 
> 
> > understrap@1.0.1 watch-run-css
> > nodemon --watch sass/ --ext scss --exec "npm-run-all css"
> 
> 
> > understrap@1.0.1 watch-run-js
> > nodemon --watch src/js/ --ext js --exec "npm-run-all js"
> 
> [nodemon] 2.0.12
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): sass/**/*
> [nodemon] watching extensions: scss
> [nodemon] 2.0.12
> [nodemon] starting `npm-run-all css`
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): src/js/**/*
> [nodemon] watching extensions: js
> [nodemon] starting `npm-run-all js`
> 
> > understrap@1.0.1 js
> > npm-run-all js-compile js-minify
> 
> 
> > understrap@1.0.1 css
> > npm-run-all css-compile css-postcss css-minify
> 
> 
> > understrap@1.0.1 js-compile
> > rollup --config src/build/rollup.config.js --sourcemap
> 
> 
> > understrap@1.0.1 css-compile
> > sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/theme.scss:css/theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css
> 
> 
> /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/src/js/bootstrap.js, /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/src/js/skip-link-focus-fix.js, /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap/src/js/custom-javascript.js → js/theme.js...
> created js/theme.js in 1.5s
> 
> > understrap@1.0.1 js-minify
> > terser  --config-file src/build/terser.config.json --output js/theme.min.js js/theme.js
> 
> 
> > understrap@1.0.1 css-postcss
> > postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"
> 
> [nodemon] clean exit - waiting for changes before restart
> 
> > understrap@1.0.1 css-minify
> > cleancss -O1 --format breakWith=lf --with-rebase --source-map --source-map-inline-sources --output css/ --batch --batch-suffix ".min" "css/*.css" "!css/*.min.css" "!css/*rtl*.css"
> 
> [nodemon] clean exit - waiting for changes before restart

So I then install the child theme from the github repo and same thing with npm install.

Then npm run watch, and get the error again:

> 
> > understrap-child@1.0.1 watch
> > npm-run-all --parallel watch-run-*
> 
> 
> > understrap-child@1.0.1 watch-run-js
> > nodemon --watch src/js/ --ext js --exec "npm-run-all js"
> 
> 
> > understrap-child@1.0.1 watch-run-css
> > nodemon --watch sass/ --ext scss --exec "npm-run-all css"
> 
> [nodemon] 2.0.13
> [nodemon] to restart at any time, enter `rs`
> [nodemon] 2.0.13
> [nodemon] watching path(s): sass/**/*
> [nodemon] watching extensions: scss
> [nodemon] to restart at any time, enter `rs`
> [nodemon] starting `npm-run-all css`
> [nodemon] watching path(s): src/js/**/*
> [nodemon] watching extensions: js
> [nodemon] starting `npm-run-all js`
> 
> > understrap-child@1.0.1 css
> > npm-run-all css-compile css-postcss css-minify
> 
> 
> > understrap-child@1.0.1 js
> > npm-run-all js-compile js-minify
> 
> 
> > understrap-child@1.0.1 css-compile
> > sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/child-theme.scss:css/child-theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css
> 
> 
> > understrap-child@1.0.1 js-compile
> > rollup --config src/build/rollup.config.js --sourcemap
> 
> 
> /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/src/js/bootstrap.js, /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/src/js/skip-link-focus-fix.js, /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/src/js/custom-javascript.js → js/child-theme.js...
> [!] (plugin babel) BrowserslistError: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
> src/js/bootstrap.js
> BrowserslistError: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
>     at unknownQuery (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:285:10)
>     at /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:372:11
>     at Array.reduce (<anonymous>)
>     at resolve (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:318:18)
>     at browserslist (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:444:21)
>     at resolveTargets (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/@babel/helper-compilation-targets/lib/index.js:168:20)
>     at getTargets (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/@babel/helper-compilation-targets/lib/index.js:213:27)
>     at resolveTargets (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/@babel/core/lib/config/resolve-targets.js:62:50)
>     at loadPrivatePartialConfig (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/@babel/core/lib/config/partial.js:112:49)
>     at loadPrivatePartialConfig.next (<anonymous>)
> 
> ERROR: "js-compile" exited with 1.
> ERROR: "js" exited with 1.
> [nodemon] app crashed - waiting for file changes before starting...
> 
> > understrap-child@1.0.1 css-postcss
> > postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"
> 
> Error [BrowserslistError]: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
>     at unknownQuery (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:285:10)
>     at /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:372:11
>     at Array.reduce (<anonymous>)
>     at resolve (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:318:18)
>     at browserslist (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/browserslist/index.js:444:21)
>     at Browsers.parse (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/autoprefixer/lib/browsers.js:54:12)
>     at new Browsers (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/autoprefixer/lib/browsers.js:42:26)
>     at loadPrefixes (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/autoprefixer/lib/autoprefixer.js:107:20)
>     at Object.prepare (/home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/autoprefixer/lib/autoprefixer.js:121:22)
>     at /home/ivancunha/Local Sites/teste5/app/public/wp-content/themes/understrap-child/node_modules/postcss/lib/lazy-result.js:149:39 {
>   browserslist: true
> }
> ERROR: "css-postcss" exited with 1.
> ERROR: "css" exited with 1.
> [nodemon] app crashed - waiting for file changes before starting...

This gives the same errors: https://github.com/understrap/understrap/issues/1473#issuecomment-947963021
Doing this in a local machine, after a restart with nothing else opened besides the terminal: https://github.com/understrap/understrap/issues/1473#issuecomment-948500875
This does nothing: https://github.com/understrap/understrap/issues/1473#issuecomment-949903119

Did this fix, fixed the understrap main repo, but it wasn't applied to the child theme repo?
https://github.com/understrap/understrap/pull/1517

Or something did get screwed in my computer?

Thanks

**Comment by ivancunha** [comment]
Tried with understrap v1.0.0 and understrap-child v1.0.0 and got the same errors

**Comment by bacoords** [comment]
This typically happens when your node version changes while in the middle of development. We typically recommend using a tool like Node Version Manager to keep track of which version your using. 

You can also just try deleting the `package-lock.json` file and the `node_modules` folder, and then running `npm install` again.

**Comment by ivancunha** [comment]
Thanks for the quick reply!! :)

I am using nvm
And all of this is occurring in brand new installations.
To write up this issue, I made about 6 new installations, and in the last 5 days I must have made about 15 installations. 
So it's not about a change in the middle of a project.

Even so, I deleted package-lock,json and node_modules once again in the original project, and nothing. I get the same errors.

Thanks

**Comment by ivancunha** [comment]
Well...
I ran LinuxMint as a LiveCD.
Installed git 2.25.1
Installed node 10.24.1 LTS with nvm
Downloaded understrap and understrap-child
Ran "npm install" and "npm run watch"
No errors......

What could be the problem I have in my machine at the moment?
Kernel version? I have 5.4.0-91-generic while on the LiveCD it had 5.4.0-74-generic
Some files from a git or node installation that aren't deleted after updating? 
Something that is globally installed and shouldn't?

I can't format this machine at the moment :\ 

Thanks

**Comment by ivancunha** [comment]
Did not find the problem.
Maybe because git was installed from source (?)
Just formatted, installed Linux Mint again, and everything else, and it all works again.
Cheers!

**Comment by bacoords** [comment]
Ah interesting. Glad it worked out!

**Comment by ivancunha** [comment]
This is getting tiring.....
Formatted and installed everything again and it worked in the basic test.
Now I'm ready to start working and pull an all nighter.... and it's not working again....
Not the same errors as before.

I'm using git v2.15.1
And nvm with npm v10.24.1

I get the same with 1.0.1 and with 1.1.0

Running "npm install" I get this:

> ivancunha@ivancunha-MacBookPro:~/Desktop/understrap-main$ npm install
> 
> > nodemon@2.0.15 postinstall /home/ivancunha/Desktop/understrap-main/node_modules/nodemon
> > node bin/postinstall || exit 0
> 
> npm WARN bootstrap@4.6.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> added 592 packages from 430 contributors and audited 594 packages in 8.833s
> 
> 73 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities

Not installing jquery? o.0

And then after running "npm run watch"

> ivancunha@ivancunha-MacBookPro:~/Desktop/understrap-main$ npm run watch
> 
> > understrap@1.1.0 watch /home/ivancunha/Desktop/understrap-main
> > npm-run-all --parallel watch-run-*
> 
> 
> > understrap@1.1.0 watch-run-js /home/ivancunha/Desktop/understrap-main
> > nodemon --watch src/js/ --ext js --exec "npm-run-all js"
> 
> 
> > understrap@1.1.0 watch-run-css /home/ivancunha/Desktop/understrap-main
> > nodemon --watch src/sass/ --ext scss --exec "npm-run-all css"
> 
> [nodemon] 2.0.15
> [nodemon] 2.0.15
> [nodemon] to restart at any time, enter `rs`
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): src/sass/**/*
> [nodemon] watching extensions: scss
> [nodemon] watching path(s): src/js/**/*
> [nodemon] watching extensions: js
> [nodemon] starting `npm-run-all css`
> [nodemon] starting `npm-run-all js`
> 
> > understrap@1.1.0 css /home/ivancunha/Desktop/understrap-main
> > npm-run-all css-compile css-postcss css-minify
> 
> 
> > understrap@1.1.0 js /home/ivancunha/Desktop/understrap-main
> > npm-run-all js-compile js-minify
> 
> 
> > understrap@1.1.0 js-compile /home/ivancunha/Desktop/understrap-main
> > rollup --config src/build/rollup.config.js --sourcemap
> 
> 
> > understrap@1.1.0 css-compile /home/ivancunha/Desktop/understrap-main
> > sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/theme.scss:css/theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css
> 
> 
> /home/ivancunha/Desktop/understrap-main/src/js/bootstrap.js, /home/ivancunha/Desktop/understrap-main/src/js/skip-link-focus-fix.js, /home/ivancunha/Desktop/understrap-main/src/js/custom-javascript.js → js/theme.js...
> created js/theme.js in 2.2s
> 
> > understrap@1.1.0 js-minify /home/ivancunha/Desktop/understrap-main
> > terser  --config-file src/build/terser.config.json --output js/theme.min.js js/theme.js
> 
> 
> > understrap@1.1.0 css-postcss /home/ivancunha/Desktop/understrap-main
> > postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"
> 
> /home/ivancunha/Desktop/understrap-main/node_modules/postcss-cli/index.js:3
> import fs from 'fs-extra'
>        ^^
> 
> SyntaxError: Unexpected identifier
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! understrap@1.1.0 css-postcss: `postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the understrap@1.1.0 css-postcss script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ivancunha/.npm/_logs/2021-12-01T23_32_55_588Z-debug.log
> ERROR: "css-postcss" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! understrap@1.1.0 css: `npm-run-all css-compile css-postcss css-minify`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the understrap@1.1.0 css script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ivancunha/.npm/_logs/2021-12-01T23_32_55_613Z-debug.log
> ERROR: "css" exited with 1.
> [nodemon] app crashed - waiting for file changes before starting...
> [nodemon] clean exit - waiting for changes before restart

And on this error message It talks about the log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/ivancunha/.nvm/versions/node/v10.24.1/bin/node',
> 1 verbose cli   '/home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/bin/npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'css' ]
> 2 info using npm@6.14.12
> 3 info using node@v10.24.1
> 4 verbose run-script [ 'precss', 'css', 'postcss' ]
> 5 info lifecycle understrap@1.1.0~precss: understrap@1.1.0
> 6 info lifecycle understrap@1.1.0~css: understrap@1.1.0
> 7 verbose lifecycle understrap@1.1.0~css: unsafe-perm in lifecycle true
> 8 verbose lifecycle understrap@1.1.0~css: PATH: /home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ivancunha/Desktop/understrap-main/node_modules/.bin:/home/ivancunha/Desktop/understrap-main/node_modules/.bin:/home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ivancunha/Desktop/understrap-main/node_modules/.bin:/home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ivancunha/Desktop/understrap-main/node_modules/.bin:/home/ivancunha/.nvm/versions/node/v10.24.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle understrap@1.1.0~css: CWD: /home/ivancunha/Desktop/understrap-main
> 10 silly lifecycle understrap@1.1.0~css: Args: [ '-c', 'npm-run-all css-compile css-postcss css-minify' ]
> 11 silly lifecycle understrap@1.1.0~css: Returned: code: 1  signal: null
> 12 info lifecycle understrap@1.1.0~css: Failed to exec css script
> 13 verbose stack Error: understrap@1.1.0 css: `npm-run-all css-compile css-postcss css-minify`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:198:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:198:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid understrap@1.1.0
> 15 verbose cwd /home/ivancunha/Desktop/understrap-main
> 16 verbose Linux 5.4.0-91-generic
> 17 verbose argv "/home/ivancunha/.nvm/versions/node/v10.24.1/bin/node" "/home/ivancunha/.nvm/versions/node/v10.24.1/lib/node_modules/npm/bin/npm-cli.js" "run" "css"
> 18 verbose node v10.24.1
> 19 verbose npm  v6.14.12
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error understrap@1.1.0 css: `npm-run-all css-compile css-postcss css-minify`
> 22 error Exit status 1
> 23 error Failed at the understrap@1.1.0 css script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]


Could this be something about permissions? On linux.... there are always permission problems...
Could this be something about an update on Linux Mint? Right after installing the SO I tested it and it worked, and a few hours later it doesn't? bah....

Thanks for any kind of help!

**Comment by bacoords** [comment]
You should probably use node version 14 or higher. I'd recommend running `nvm use 14` then deleting node_modules and running `npm install` again. Typically every time you open your project you'll want to make sure you're using the same version of node every time.

**Comment by ivancunha** [comment]
You were fast replying... and if I read what you wrote before I formatted everything again..... arrgg!!
So, formatted everything again, and with nothing installed except for git and nvm... downloaded understrap's zip grom github and started testing.
That was it.
npm 10.x.x same errors.
npm 14.x.x no errors.

Thanks again :)
