### ISSUE TITLE
Immediate errors when running npm watch on fresh install

### ISSUE THREAD

**Issue by grzybowski1911** [understrap/understrap#1559]
I’ve been using understrap for a long time and have always loved it. But now with the 1.0 update I can no longer get anything to compile. No idea what I’m doing wrong.

Understrap version: 1.1.0
Understrap: trying to run $ npm run watch on parent theme
GIT version: git version 2.33.0 1.1.0
NPM version: 7.6.0
NODE version: v14.12.0

What I’m doing:

Step 1: Install understrap via $ git clone https://github.com/understrap/understrap.git

Step 2: Navigate to new understrap directory $ cd understrap

Step 3: Install dependencies $ npm install

Step 4: Start watch script $ npm run watch

Step 5: Try to determine what the Output is trying to tell me from run watch...

```
> understrap@1.1.0 watch
> npm-run-all --parallel watch-run-*


> understrap@1.1.0 watch-run-css
> nodemon --watch src/sass/ --ext scss --exec "npm-run-all css"


> understrap@1.1.0 watch-run-js
> nodemon --watch src/js/ --ext js --exec "npm-run-all js"

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/js/**/*
[nodemon] watching extensions: js
[nodemon] starting `npm-run-all js`
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/sass/**/*
[nodemon] watching extensions: scss
[nodemon] starting `npm-run-all css`

> understrap@1.1.0 js
> npm-run-all js-compile js-minify


> understrap@1.1.0 css
> npm-run-all css-compile css-postcss css-minify


> understrap@1.1.0 js-compile
> rollup --config src/build/rollup.config.js --sourcemap


> understrap@1.1.0 css-compile
> sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/theme.scss:css/theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css


/Users/amp/Desktop/understrap/src/js/bootstrap.js, /Users/amp/Desktop/understrap/src/js/skip-link-focus-fix.js, /Users/amp/Desktop/understrap/src/js/custom-javascript.js → js/theme.js...
created js/theme.js in 2.4s

> understrap@1.1.0 js-minify
> terser  --config-file src/build/terser.config.json --output js/theme.min.js js/theme.js


> understrap@1.1.0 css-postcss
> postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:756:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
ERROR: "css-postcss" exited with 1.
ERROR: "css" exited with 1.
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] clean exit - waiting for changes before restart
```

I also have a legacy version 0.9.4 that I used to use that no longer works either ( Seems like Gulp isn’t being included? Probably due to the update and it being removed as a dependency? Not sure… $ gulp watch is working fine and compiling as expected on some other local sites I set up last year ) 

I'm using local by flywheel for my dev environment, not sure if that helps... 

Thanks.

**Comment by pattonwebz** [comment]
What is the output of `npm --version`?

**Comment by bacoords** [comment]
The latest version I believe only uses node 16. If using nvm, you can try running `nvm use 16` before you do `npm install`, etc.

**Comment by grzybowski1911** [comment]
Looks like it was because node was on version 14... should have checked that... 

Thank you! @bacoords
