### ISSUE TITLE
gulp copy-assets error preventing "npm install understrap" from completing

### ISSUE THREAD

**Issue by firelite** [understrap/understrap#257]
I am getting an install error on my mac when running `npm install understrap`.  Please see the following log:

```
...
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/formidable
npm http 304 https://registry.npmjs.org/formidable

> understrap@0.5.7 postinstall /Users/public/wp-content/themes/understrap/node_modules/understrap
> gulp copy-assets


/Users/public/wp-content/themes/understrap/node_modules/understrap/node_modules/gulp-sourcemaps/node_modules/strip-bom/index.js:2
module.exports = x => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/public/wp-content/themes/understrap/node_modules/understrap/node_modules/gulp-sourcemaps/src/init/index.internals.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! understrap@0.5.7 postinstall: `gulp copy-assets`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the understrap@0.5.7 postinstall script.
npm ERR! This is most likely a problem with the understrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp copy-assets
npm ERR! You can get their info via:
npm ERR!     npm owner ls understrap
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 16.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "understrap"
npm ERR! cwd /Users/public/wp-content/themes/understrap
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/public/wp-content/themes/understrap/npm-debug.log
npm ERR! not ok code 0
```

Thanks for looking into this issue.

**Comment by holger1411** [comment]
Hi!
Pls update your node install. 
You use v0.10.28 which is very very old and outdated.  v6.10 + is the latest stable version.

And make sure you have Gulp installed globally on your system.
To do so type this:
`npm install gulp -g`
into your terminal and hit enter

**Comment by firelite** [comment]
Hi Holger,

Updating Node to v7.6.0 has allowed me to run `npm install understrap` without errors, but after running the command, my current working directory still remains empty.  Is it supposed to download all the files as shown in this repo?

**Comment by holger1411** [comment]
Could be a access/permission issue.
The easierst way:
Hit the green "clone or download" button here:
https://github.com/holger1411/understrap /upper right corner)
Extract the .zip file, open the understrap folder in your terminal and than type in
`npm install understrap`
That will download all dependencies and will move any needed file in place.

**Comment by axlright** [comment]
Closing this issue since it hasn't been active in over a year and since `npm install` has been functioning well for others. Please comment if this issue persists and can re-open the issue.
