### ISSUE TITLE
Child theme update process breaks at `npm install`: `Error: Cannot find module './gulpconfig.json'`

### ISSUE THREAD

**Issue by jaredsnider** [understrap/understrap#601]
## I'm submitting a ...
  - [x] bug report

## Please tell us about your environment:

  - WordPress Version: 4.9.4
  - Browser: [ all ]
  - Language: [ all ]

---

### *Who* is the bug affecting?
The designer/developer building with Understrap Parent/Child

### *What* is affected by this bug?
Child theme update process breaks at `npm install`

### *When* does this occur?
At `npm install` step of updating understrap-child

### *Where* on the platform does it happen?
`npm install`

### *How* do we replicate the issue?
1. Update parent theme
2. Copy/overwrite `gulpfile.js` and `package.json` from Parent into Child
3. Run npm install inside Child
4. Receive error `Error: Cannot find module './gulpconfig.json'`

### Expected behavior (i.e. solution)
`npm install` finishes successfully

### Other Comments
Full error text:
```
$ npm install

> understrap@0.8.1 postinstall /Users/MY-USER-PATH/wp-content/themes/understrap-child
> gulp copy-assets

module.js:540
    throw err;
    ^

Error: Cannot find module './gulpconfig.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/MY-USER-PATH/wp-content/themes/understrap-child/gulpfile.js:25:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.8.1 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MY-USER-PATH/.npm/_logs/DEBUG-LOG-NAME-debug.log
```

**Comment by jaredsnider** [comment]
I am not sure why my child them was missing `gulpconfig.json`, but I copied that as well as `gulpfile.js` and `package.json` from a fresh version of understrap-child and its working fine. Please pardon my human error and erroneous issue posting.
