### ISSUE TITLE
gulp copy-assets failed

### ISSUE THREAD

**Issue by bashfulbirdie** [understrap/understrap#612]
Got this after attempting to run npm install on a clean understrap theme.

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/lisacartrette/sites/clients/bmgasdata_html/wp-content/themes/bmgasdata/node_modules/gulp-sourcemaps/node_modules/source-map/source-map.js:7:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! understrap@0.8.1 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap@0.8.1 postinstall script 'gulp copy-assets'.
npm ERR! This is most likely a problem with the understrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp copy-assets
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs understrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls understrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lisacartrette/sites/clients/bmgasdata_html/wp-content/themes/bmgasdata/npm-debug.log

**Comment by 0dp** [comment]
```
npm ERR! node v4.4.3
npm ERR! npm v2.15.1
```
Could you try and update your node and npm and report back?

**Comment by 0dp** [comment]
@bashfulbirdie you there?

**Comment by Thomas-A-Reinert** [comment]
Closing abandoned issues. @bashfulbirdie - feel free to reopen if the problem persists.
