### ISSUE TITLE
gulp copy-assets error with gulp.series function

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#731]
@0dp:  Tried to update UnderStrap and to release 0.8.2. There is a new function called gulp.series in gulpfile.js which is not defined. 
## Issue is about..
  - [x ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **Node.js & NPM Versions:** Node.js [V 6.11.1] | NPM [V 3.10.10]

---

# Issue Overview for Bugreports
gulp.series is not a function error message while running gulp copy-assets
Error message:
TypeError: gulp.series is not a function
    at Object.<anonymous> (/Users/koenemann/Documents/git/understrap/gulpfile.js:162:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:26:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:173:63)

## Steps to reproduce?
run gulp copy-assets in terminal

 * Test
 * Documentation

**Comment by 0dp** [comment]
@holger1411 
Did you update gulp first?

Output of `gulp -v` should read
```
gulp -v
[13:42:30] CLI version 2.0.1
[13:42:30] Local version 4.0.0
```

After update it should work as expected

**Comment by holger1411** [comment]
Ah okay, I was on 3.9.1.
👍
