### ISSUE TITLE
gulp watch error on centos 6.1

### ISSUE THREAD

**Issue by dave-watts** [understrap/understrap#848]
Please delete anything that does not apply for you!

## Issue is about..

 I need help

## Please tell us about your environment:

centos 6.1 x86_64 GNU/Linux
npm 4.0.3 
node v0.10.48
gulp [01:05:53] CLI version 3.9.1 [01:05:53] Local version 3.9.1

# Issue Overview for Bugreports

When running gulp in theme, I get the following error
------------------------------------------------------
[/public_html/wp-content/themes/understrap]# gulp watch

/public_html/wp-content/themes/understrap/node_modules/gulp-sass/index.js:15
const gulpSass = (options, sync) => through.obj((file, enc, cb) => { // eslint
                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/advertsclub/public_html/wp-content/themes/understrap/gulpfile.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

## Steps to reproduce?

Standard install via git clone

## *What* is affected by this bug?

unable to use gulp

## Expected behavior

stef@dev:understrap$ gulp watch
[13:06:47] Using gulpfile ~/projects/php/wordpress/wp-content/themes/understrap/gulpfile.js
[13:06:47] Starting 'watch'...
[13:06:47] Finished 'watch' after 12 ms

**Comment by Thomas-A-Reinert** [comment]
Just to make sure: When I run ( In my actual understrap environment)
`node --version`
.. the result is: `v10.12.0` And NOT `node v0.10.48` which is like 10 version below. Which would explain a LOT and node.js not being able to process ES6 code ;)

**Comment by dave-watts** [comment]
I must have updated node, because now when I run node version I get
node --version
v7.2.1
do you think that's that still too low?

**Comment by holger1411** [comment]
Closing this because it seems to be resolved
