### ISSUE TITLE
Can't install dependencies using npm-install

### ISSUE THREAD

**Issue by tharindutpk** [understrap/understrap#867]
I download the latest copy of Understrap and tried to install dependencies using `npm install
` but it throws me a big bloat.

## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [x] I need help

## Please tell us about your environment:

  - **OS Version:** MacOS Mojave
  - **Node.js & NPM Versions:** Node.js [V 11.3.0] | NPM [V 6.4.1]

````
> understrap@0.8.8 postinstall /Users/tharindu/Downloads/understrap-0.8.8
> gulp copy-assets

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.8.8 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.8.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tharindu/.npm/_logs/2018-12-10T12_46_44_370Z-debug.log
 ✘ ✝  ~/Downloads/understrap-0.8.8  npm install

> fsevents@1.2.4 install /Users/tharindu/Downloads/understrap-0.8.8/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.3.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/tharindu/.node-gyp/11.3.0/include/node/v8.h:5241:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/tharindu/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1063:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/tharindu/.node-gyp/11.3.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/tharindu/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1073:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/tharindu/.node-gyp/11.3.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/tharindu/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
4 warnings generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/tharindu/Downloads/understrap-0.8.8/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> node-sass@4.9.4 install /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/darwin-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/darwin-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.4 postinstall /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/11.3.0_1/bin/node /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/11.3.0_1/bin/node',
gyp verb cli   '/Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.3.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:13:12)\n    at F (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:68:19)\n    at E (/Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:80:29)\n    at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/which/which.js:89:16\n    at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/isexe/index.js:42:5\n    at /Users/tharindu/Downloads/understrap-0.8.8/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.10
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 11.3.0
gyp verb command install [ '11.3.0' ]
gyp verb install input version string "11.3.0"
gyp verb install installing version: 11.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 11.3.0
gyp verb build dir attempting to create "build" dir: /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tharindu/.node-gyp/11.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tharindu/.node-gyp/11.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/tharindu/.node-gyp/11.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tharindu/Downloads/understrap-0.8.8/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/tharindu/.node-gyp/11.3.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/Users/tharindu/.node-gyp/11.3.0/include/node -I/Users/tharindu/.node-gyp/11.3.0/src -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/config -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/openssl/include -I/Users/tharindu/.node-gyp/11.3.0/deps/uv/include -I/Users/tharindu/.node-gyp/11.3.0/deps/zlib -I/Users/tharindu/.node-gyp/11.3.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/Users/tharindu/.node-gyp/11.3.0/include/node -I/Users/tharindu/.node-gyp/11.3.0/src -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/config -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/openssl/include -I/Users/tharindu/.node-gyp/11.3.0/deps/uv/include -I/Users/tharindu/.node-gyp/11.3.0/deps/zlib -I/Users/tharindu/.node-gyp/11.3.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o ../src/libsass/src/ast_fwd_decl.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/Users/tharindu/.node-gyp/11.3.0/include/node -I/Users/tharindu/.node-gyp/11.3.0/src -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/config -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/openssl/include -I/Users/tharindu/.node-gyp/11.3.0/deps/uv/include -I/Users/tharindu/.node-gyp/11.3.0/deps/zlib -I/Users/tharindu/.node-gyp/11.3.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/backtrace.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/backtrace.o ../src/libsass/src/backtrace.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/Users/tharindu/.node-gyp/11.3.0/include/node -I/Users/tharindu/.node-gyp/11.3.0/src -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/config -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/openssl/include -I/Users/tharindu/.node-gyp/11.3.0/deps/uv/include -I/Users/tharindu/.node-gyp/11.3.0/deps/zlib -I/Users/tharindu/.node-gyp/11.3.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/base64vlq.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/base64vlq.o ../src/libsass/src/base64vlq.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/Users/tharindu/.node-gyp/11.3.0/include/node -I/Users/tharindu/.node-gyp/11.3.0/src -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/config -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/openssl/include -I/Users/tharindu/.node-gyp/11.3.0/deps/uv/include -I/Users/tharindu/.node-gyp/11.3.0/deps/zlib -I/Users/tharindu/.node-gyp/11.3.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/bind.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/bind.o ../src/libsass/src/bind.cpp
  cc '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/Users/tharindu/.node-gyp/11.3.0/include/node -I/Users/tharindu/.node-gyp/11.3.0/src -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/config -I/Users/tharindu/.node-gyp/11.3.0/deps/openssl/openssl/include -I/Users/tharindu/.node-gyp/11.3.0/deps/uv/include -I/Users/tharindu/.node-gyp/11.3.0/deps/zlib -I/Users/tharindu/.node-gyp/11.3.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/cencode.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/cencode.o ../src/libsass/src/cencode.c
../src/libsass/src/cencode.c:50:5: warning: declaration does not declare anything [-Wmissing-declarations]
__attribute__ ((fallthrough));
````

**Comment by tharindutpk** [comment]
Thank you @0dp! I did exactly how you asked and I'm getting this error.

````
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gulp-sass@^4.11.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'understrap'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tharindu/.npm/_logs/2018-12-10T17_12_59_620Z-debug.log
````

**Comment by 0dp** [comment]
please tell me the output of `gulp -v`

**Comment by 0dp** [comment]
From a freshly downloaded copy of understrap-0.8.8
```
➜  understrap-0.8.8 npm install

> fsevents@1.2.4 install /Users/odp/Desktop/understrap-0.8.8/node_modules/fsevents
> node install

[fsevents] Success: "/Users/odp/Desktop/understrap-0.8.8/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.4 install /Users/odp/Desktop/understrap-0.8.8/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/odp/.npm/node-sass/4.9.4/darwin-x64-64_binding.node

> node-sass@4.9.4 postinstall /Users/odp/Desktop/understrap-0.8.8/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/odp/Desktop/understrap-0.8.8/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /Users/odp/Desktop/understrap-0.8.8/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /Users/odp/Desktop/understrap-0.8.8/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/odp/Desktop/understrap-0.8.8/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> understrap@0.8.8 postinstall /Users/odp/Desktop/understrap-0.8.8
> gulp copy-assets

[18:39:06] Using gulpfile ~/Desktop/understrap-0.8.8/gulpfile.js
[18:39:06] Starting 'copy-assets'...
[18:39:06] Finished 'copy-assets' after 9.46 ms
added 1238 packages from 703 contributors and audited 14193 packages in 15.182s
found 11 vulnerabilities (1 low, 6 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
➜  understrap-0.8.8 gulp -v
[18:39:35] CLI version 2.0.1
[18:39:35] Local version 3.9.1
➜  understrap-0.8.8
```

I think we have a local issue on your end 😃

**Comment by tharindutpk** [comment]
My npm and node versions as follows,

````
v11.3.0
npm 6.4.1
````

**Comment by johavik** [comment]
@tharindutpk Check if you actually added `"node-sass": "^4.11.0"` to your package.json. From your output, it looks like you added `"gulp-sass@^4.11.0"`.

FWIW - I had the same problem as @tharindutpk - adding `"node-sass": "^4.11.0"` to package.json helped. This is on a fresh node / npm install via homebrew.

**Comment by tharindutpk** [comment]
@johavik and @0dp thank you for pointing that out. Actually, you were right, I had changed gulp-sass without adding the "node-sass": "^4.11.0" as a dependency. Now it seems to work like charm.

Thank you again!

**Comment by AlexSigurdar** [comment]
Hmm.. stil doesn't work for me! Have removed node_modules and package-lock.json, added "node-sass": "^4.11.0" and removed gulp-sass :/ 

My package.json: 
{
  "name": "understrap",
  "version": "0.8.8",
  "description": "WordPress Theme framework",
  "main": "index.js",
  "scripts": {
    "postinstall": "gulp copy-assets"
  },
  "engines": {
    "npm": ">=2.1.8"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/holger1411/understrap.git"
  },
  "keywords": [
    "wordpress",
    "theme",
    "framework",
    "bootstrap",
    "underscores"
  ],
  "author": "Holger Koenemann",
  "license": "GPL-2.0",
  "bugs": {
    "url": "https://github.com/holger1411/understrap/issues"
  },
  "homepage": "https://understrap.com",
  "dependencies": {
    "bootstrap": "4.1.3",
    "browser-sync": "^2.23.6",
    "del": "^3.0.0",
    "font-awesome": "^4.7.0",
    "gulp": "3.9.1",
    "gulp-autoprefixer": "6.0.0",
    "gulp-clean-css": "^3.9.2",
    "gulp-clone": "2.0.1",
    "gulp-concat": "^2.6.1",
    "gulp-cssnano": "^2.1.2",
    "gulp-ignore": "^2.0.2",
    "gulp-imagemin": "^4.1.0",
    "gulp-merge": "^0.1.1",
    "gulp-plumber": "^1.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "1.0.0",
    "gulp-rimraf": "^0.2.2",
    "gulp-sass": "^4.0.2",
    "gulp-sequence": "1.0.0",
    "gulp-sourcemaps": "2.6.4",
    "gulp-uglify": "^3.0.0",
    "gulp-watch": "5.0.1",
    "merge2": "^1.2.1",
    "node-sass": "^4.11.0",
    "run-sequence": "^2.2.1",
    "undescores-for-npm": "^1.0.0"
  }
}


ERROR: 

Error: EPERM: operation not permitted, chmod '/Applications/XAMPP/xamppfiles/htdocs/bethke/wordpress/wp-content/themes/understrap/sr
c/sass/bootstrap4/_alert.scss'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.8.8 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.8.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexandrasigurdardottir/.npm/_logs/2018-12-20T14_07_20_647Z-debug.log

**Comment by pattonwebz** [comment]
@AlexSigurdar your issue looks a bit different to OPs. I think your issues is related to the file and folder permissions you have in the runup to the files that gulp is trying to modify.

This line here indicates a permission error when it tries to use `chmod` on the file mentioned.
```
Error: EPERM: operation not permitted, chmod '/Applications/XAMPP/xamppfiles/htdocs/bethke/wordpress/wp-content/themes/understrap/sr
c/sass/bootstrap4/_alert.scss'
```
Sorry that my reply is not a solution for you but maybe highlighting this will help lead to the right fix for you.
