### ISSUE TITLE
gulp copy-assets error on 'events.js'

### ISSUE THREAD

**Issue by FlashyDevBR** [understrap/understrap#889]
I've installed Understrap on themes option on my wordpress local website, already have the required things.

So, next I've entered on theme folder and typed npm-install, everything got completed, but on gulp copy-assets got a error:

```
flashy@flashy-PC:/var/www/html/site_basic/wp-content/themes/understrap$ gulp copy-assets
[08:56:00] Using gulpfile /var/www/html/site_basic/wp-content/themes/understrap/gulpfile.js
[08:56:00] Starting 'copy-assets'...
[08:56:00] Finished 'copy-assets' after 15 ms
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, chmod '/var/www/html/site_basic/wp-content/themes/understrap/src/sass/bootstrap4/_alert.scss'
Emitted 'error' event at:
    at DestroyableTransform.onerror (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:182:13)
    at onwriteError (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at done (/var/www/html/site_basic/wp-content/themes/understrap/node_modules/vinyl-fs/lib/dest/writeContents/index.js:11:7)
    at FSReqWrap.oncomplete (fs.js:136:20)
```

I already give permission, even tried a sudo chmod -R 777 on the understrap folder, but the error continues, also tried to copy the code of gulpfile.js from github and updated there but no solution, how i can fix this please ?

If i need to give some more information i'm sorry, first time using this tool and request me the info please.

PS: My OP is a Linux Deepin 15.5

**Comment by 0dp** [comment]
what is the output of `gulp -v`

**Comment by FlashyDevBR** [comment]
> what is the output of `gulp -v`
> Also have you read this, [dlmanning/gulp-sass#657](https://github.com/dlmanning/gulp-sass/issues/657)
> 
> I do not encourage you to run gulp as root or sudo.
> 
> Did you by any chance install gulp-cli with `sudo npm install gulp-cli -g`?
> You should not use sudo to install global packages. So try and remove gulp-cli and install it again without sudo `npm install gulp-cli -g`

The output is:

```
[13:50:19] CLI version 2.0.1
[13:50:19] Local version 3.9.1

```

And im not using sudo with npm nor gulp

**Comment by 0dp** [comment]
Ok, can you try and run `npm cache clean` to clean the npm cache?

**Comment by FlashyDevBR** [comment]
> Ok, can you try and run `npm cache clean` to clean the npm cache?

I've tried but got this output

```
flashy@flashy-PC:/var/www/html/site_basic/wp-content/themes/understrap$ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flashy/.npm/_logs/2019-01-07T18_39_53_460Z-debug.log

```

**Comment by 0dp** [comment]
Ok try and verify the cache as explained

**Comment by 0dp** [comment]
Who owns the folder? I know you said you 0777 the folder but who is the owner?

**Comment by FlashyDevBR** [comment]
> Ok try and verify the cache as explained

How I can verify ?

> Who owns the folder? I know you said you 0777 the folder but who is the owner?

`drwxrwxrwx 17 www-data www-data 4096 Jan  7 08:35 understrap `

**Comment by FlashyDevBR** [comment]
I need to change the ownership to my username or it being www-data doenst need change ?

**Comment by 0dp** [comment]
npm cache verify

Yeah could you try and make your primary user the owner of the files.

I am certain it's a local permission issue

**Comment by Thomas-A-Reinert** [comment]
Does the problem still persist? As there hasn´t be a follow-up for ´bout half a year, I´m going to close this issue.

If the problem still persists, please get back to it supplying additional info.
