### ISSUE TITLE
Install NPM module don't work

### ISSUE THREAD

**Issue by zafon18** [understrap/understrap#916]
Hey, I have a problem with installing the AOS module from the npm package. I added dependence through 
``` npm install aos --save ``` and edited the gulpfile.js file by adding 
```
gulp.task( 'copy-assets', function() { 
// Adding AOS
            gulp.src( paths.node + 'aos/src/js/aos.js' )
                .pipe( gulp.dest( paths.dev + '/js' ) );
});
```
Then I added in ```
gulp.task( 'scripts', function() {
 paths.dev + '/js/aos.js'

next step run
```
gulp copy-assets
```
and 
```
gulp scripts
```
[13:07:59] Using gulpfile ~\Downloads\Under\node_modules\understrap\gulpfile.js
[13:07:59] Starting 'copy-assets'...
[13:07:59] Finished 'copy-assets' after 13 ms
```
Gulp -v
CLI version 2.0.1
Local version 3.9.1
```
```
node -v
v10.15.1
```
but nothing is generated. Can I help me?

_Originally posted by @zafon18 in https://github.com/understrap/understrap/issues/772#issuecomment-463174789_

**Comment by 0dp** [comment]
Have you checked that the aos.js is present in /src/

**Comment by zafon18** [comment]
> Czy sprawdziłeś, że aos.js jest obecny w / src /

It does not automatically create, but an error occurs when you copy it to the / src / js directory
```
GulpUglifyError: unable to minify JavaScript
    at createError (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at apply (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\lodash\_apply.js:16:25)
    at wrapper (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\lodash\_createCurry.js:41:12)
    at C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\gulp-uglify\lib\minify.js:55:15
    at DestroyableTransform._transform (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\gulp-uglify\composer.js:12:19)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:334:11)
Emitted 'error' event at:
    at DestroyableTransform.onerror (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:182:13)
    at onwriteError (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:443:12)
    at onwrite (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:470:11)
    at WritableState.onwrite (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:93:3)
    at DestroyableTransform._transform (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\gulp-uglify\composer.js:16:7)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\xampp\htdocs\wordpress\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:428:64)
```

I have no idea what is going on

**Comment by 0dp** [comment]
ahh yes I see.

You need to include the aos.js file from the dist/ folder so
```
// Adding AOS
            gulp.src( paths.node + 'aos/dist/aos.js' )
                .pipe( gulp.dest( paths.dev + '/js' )
```

**Comment by zafon18** [comment]
Yea,
Its work. Thank for solution. @0dp 
The last question of the aos.css file should be added to _theme.scss or do the same as with .js, of course, asking for a .css file

**Comment by 0dp** [comment]
I would do the same with the css file. Add it to copy-assets task, then include it in _theme.scss

**Comment by holger1411** [comment]
Hey guy, seems this is fixed. Closing it. Feel free to reopen
